### ISSUE TITLE
Can't install Gem

### ISSUE THREAD

**Issue by Ponchoalfonso** [elifoster/mojang-rb#1]
Hello, I want to use this API/Gem but when I run "$ gem install mojang" I get the following issue
ERROR:  Error installing mojang:
ERROR: Failed to build gem native extension.

I'm using ruby 2.2.4 on Windows 10
Maybe I should try to install it on Ubuntu

Here is more information about the error
[log.zip](https://github.com/elifoster/mojang-rb/files/768155/log.zip)

Edit, in case of link rot:
### Contents of log.zip
gem_make.out:
```
current directory: C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/curb-0.9.3/ext
C:/RailsInstaller/Ruby2.2.0/bin/ruby.exe -r ./siteconf20170210-2924-wzm6dn.rb extconf.rb
checking for curl-config... no
checking for main() in -lcurl... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=C:/RailsInstaller/Ruby2.2.0/bin/$(RUBY_BASE_NAME)
	--with-curl-dir
	--without-curl-dir
	--with-curl-include
	--without-curl-include=${curl-dir}/include
	--with-curl-lib
	--without-curl-lib=${curl-dir}/lib
	--with-curllib
	--without-curllib
extconf.rb:18:in `<main>':   Can't find libcurl or curl/curl.h (RuntimeError)

  Try passing --with-curl-dir or --with-curl-lib and --with-curl-include
  options to extconf.

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/curb-0.9.3/mkmf.log

extconf failed, exit code 1
```

mkmf.log:
```
find_executable: checking for curl-config... -------------------- no

--------------------

have_library: checking for main() in -lcurl... -------------------- no

"gcc -o conftest.exe -IC:/RailsInstaller/Ruby2.2.0/include/ruby-2.2.0/i386-mingw32 -IC:/RailsInstaller/Ruby2.2.0/include/ruby-2.2.0/ruby/backward -IC:/RailsInstaller/Ruby2.2.0/include/ruby-2.2.0 -I. -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64   -O3 -fno-omit-frame-pointer -fno-fast-math -g -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat conftest.c  -L. -LC:/RailsInstaller/Ruby2.2.0/lib -L.      -lmsvcrt-ruby220  -lshell32 -lws2_32 -liphlpapi -limagehlp -lshlwapi  "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <winsock2.h>
4: #include <windows.h>
5: int main(int argc, char **argv)
6: {
7:   return 0;
8: }
/* end */

"gcc -o conftest.exe -IC:/RailsInstaller/Ruby2.2.0/include/ruby-2.2.0/i386-mingw32 -IC:/RailsInstaller/Ruby2.2.0/include/ruby-2.2.0/ruby/backward -IC:/RailsInstaller/Ruby2.2.0/include/ruby-2.2.0 -I. -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64   -O3 -fno-omit-frame-pointer -fno-fast-math -g -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat conftest.c  -L. -LC:/RailsInstaller/Ruby2.2.0/lib -L.      -lmsvcrt-ruby220 -lcurl  -lshell32 -lws2_32 -liphlpapi -limagehlp -lshlwapi  "
conftest.c: In function 't':
conftest.c:16:32: warning: variable 'p' set but not used [-Wunused-but-set-variable]
c:/railsinstaller/devkit/mingw/bin/../lib/gcc/i686-w64-mingw32/4.7.2/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lcurl
collect2.exe: error: ld returned 1 exit status
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #include <winsock2.h>
 4: #include <windows.h>
 5: 
 6: /*top*/
 7: extern int t(void);
 8: int main(int argc, char **argv)
 9: {
10:   if (argc > 1000000) {
11:     printf("%p", &t);
12:   }
13: 
14:   return 0;
15: }
16: int t(void) { void ((*volatile p)()); p = (void ((*)()))main; return 0; }
/* end */

"gcc -o conftest.exe -IC:/RailsInstaller/Ruby2.2.0/include/ruby-2.2.0/i386-mingw32 -IC:/RailsInstaller/Ruby2.2.0/include/ruby-2.2.0/ruby/backward -IC:/RailsInstaller/Ruby2.2.0/include/ruby-2.2.0 -I. -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64   -O3 -fno-omit-frame-pointer -fno-fast-math -g -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat conftest.c  -L. -LC:/RailsInstaller/Ruby2.2.0/lib -L.      -lmsvcrt-ruby220 -lcurl  -lshell32 -lws2_32 -liphlpapi -limagehlp -lshlwapi  "
conftest.c: In function 't':
conftest.c:16:1: error: too few arguments to function 'main'
conftest.c:8:5: note: declared here
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #include <winsock2.h>
 4: #include <windows.h>
 5: 
 6: /*top*/
 7: extern int t(void);
 8: int main(int argc, char **argv)
 9: {
10:   if (argc > 1000000) {
11:     printf("%p", &t);
12:   }
13: 
14:   return 0;
15: }
16: int t(void) { main(); return 0; }
/* end */

--------------------
```

**Comment by elifoster** [comment]
Are you able to install `curb` and `oj` independently (`mojang`'s dependencies)? `mojang` itself does not have any native extensions, but both of those do if I recall correctly.

**Comment by elifoster** [comment]
@Ponchoalfonso It looks like you don't have curl installed. What is the output of `$ curl --version`?

**Comment by Ponchoalfonso** [comment]
Hello again, it has been almost a month since I asked for help and I want to apologize because of that :disappointed:
I'm glad you are helping me.
Now I'm working on Ubuntu 16.04 with RVM 1.29.1 using Ruby 2.3.0, I tryed to install the gem but I have the same problem.
I'm not able to install curb I get this problem:
```
ERROR:  Error installing curb:
	ERROR: Failed to build gem native extension.
```

Here is the full report:
[gem_make.out.tar.gz](https://github.com/elifoster/mojang-rb/files/826454/gem_make.out.tar.gz)

When I do `$ curl --version` I get the following:

```
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 
```

Sorry for answering after 23 days, I really appreciate your help.

Eli Edit:
gem_make.out:
```
current directory: /home/ponchoalfonso/.rvm/gems/ruby-2.3.0/gems/curb-0.9.3/ext
/home/ponchoalfonso/.rvm/rubies/ruby-2.3.0/bin/ruby -r ./siteconf20170307-21150-10eis66.rb extconf.rb
checking for curl-config... no
checking for main() in -lcurl... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/ponchoalfonso/.rvm/rubies/ruby-2.3.0/bin/$(RUBY_BASE_NAME)
	--with-curl-dir
	--without-curl-dir
	--with-curl-include
	--without-curl-include=${curl-dir}/include
	--with-curl-lib
	--without-curl-lib=${curl-dir}/lib
	--with-curllib
	--without-curllib
extconf.rb:18:in `<main>':   Can't find libcurl or curl/curl.h (RuntimeError)

  Try passing --with-curl-dir or --with-curl-lib and --with-curl-include
  options to extconf.

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/ponchoalfonso/.rvm/gems/ruby-2.3.0/extensions/x86_64-linux/2.3.0/curb-0.9.3/mkmf.log

extconf failed, exit code 1
```

**Comment by elifoster** [comment]
Try `sudo apt-get install libcurl3 libcurl3-gnutls libcurl4-openssl-dev`

**Comment by Ponchoalfonso** [comment]
It's working now! Thanks alot for your help! :smile:
